version: '3'

services:
  db:
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - ./.db:/var/opt/mssql/
      - /var/opt/mssql/data
    ports:
      - 1433:1433
      - 1434:1434
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TroCarAsenhADOSQL@
