version: '3.7'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - ./.db:/var/opt/mssql/
      - ./data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: secret000@
      SERVICE_TAGS: dev
      SERVICE_NAME: mssql
    ports:
      - 1433:1433
    networks:
      network:
        ipv4_address: 10.1.0.5
volumes:
  db-data:

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
